services:
  web:
    build:
      context: ./web
    networks:
      - appnet

  proxy:
    build:
      context: ./proxy
    ports:
      - "1080:80"
    depends_on:
      - web
      - api
      - stream
    networks:
      - appnet  

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    networks:
      - appnet

  stream:
    build:
      context: ./stream
    ports:
      - "4000:3000"
    networks:
      - appnet

  redis:
    image: redis:7
networks:
  appnet:
    driver: bridge